//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from myC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ImyCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class myCBaseListener : ImyCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] myCParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] myCParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] myCParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] myCParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribuicao([NotNull] myCParser.AtribuicaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribuicao([NotNull] myCParser.AtribuicaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloco([NotNull] myCParser.BlocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloco([NotNull] myCParser.BlocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] myCParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] myCParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.incremento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncremento([NotNull] myCParser.IncrementoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.incremento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncremento([NotNull] myCParser.IncrementoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecls([NotNull] myCParser.DeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecls([NotNull] myCParser.DeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncao([NotNull] myCParser.FuncaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncao([NotNull] myCParser.FuncaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.declaracao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaracao([NotNull] myCParser.DeclaracaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.declaracao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaracao([NotNull] myCParser.DeclaracaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentos([NotNull] myCParser.ArgumentosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentos([NotNull] myCParser.ArgumentosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] myCParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] myCParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.identificador"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentificador([NotNull] myCParser.IdentificadorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.identificador"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentificador([NotNull] myCParser.IdentificadorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] myCParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] myCParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.negacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegacao([NotNull] myCParser.NegacaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.negacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegacao([NotNull] myCParser.NegacaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expressao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressao([NotNull] myCParser.ExpressaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expressao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressao([NotNull] myCParser.ExpressaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperador([NotNull] myCParser.OperadorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperador([NotNull] myCParser.OperadorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermo([NotNull] myCParser.TermoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermo([NotNull] myCParser.TermoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_aritmetica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_aritmetica([NotNull] myCParser.Expr_aritmeticaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_aritmetica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_aritmetica([NotNull] myCParser.Expr_aritmeticaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_relacional([NotNull] myCParser.Expr_relacionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_relacional([NotNull] myCParser.Expr_relacionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador_logico"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperador_logico([NotNull] myCParser.Operador_logicoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador_logico"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperador_logico([NotNull] myCParser.Operador_logicoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.condicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicao([NotNull] myCParser.CondicaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.condicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicao([NotNull] myCParser.CondicaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_logica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_logica([NotNull] myCParser.Expr_logicaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_logica"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_logica([NotNull] myCParser.Expr_logicaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.condicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicional([NotNull] myCParser.CondicionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.condicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicional([NotNull] myCParser.CondicionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] myCParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] myCParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetorno([NotNull] myCParser.RetornoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetorno([NotNull] myCParser.RetornoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.chamada_funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChamada_funcao([NotNull] myCParser.Chamada_funcaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.chamada_funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChamada_funcao([NotNull] myCParser.Chamada_funcaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.entrada"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntrada([NotNull] myCParser.EntradaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.entrada"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntrada([NotNull] myCParser.EntradaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.saida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSaida([NotNull] myCParser.SaidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.saida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSaida([NotNull] myCParser.SaidaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.selecao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelecao([NotNull] myCParser.SelecaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.selecao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelecao([NotNull] myCParser.SelecaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.casos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCasos([NotNull] myCParser.CasosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.casos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCasos([NotNull] myCParser.CasosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperador_relacional([NotNull] myCParser.Operador_relacionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperador_relacional([NotNull] myCParser.Operador_relacionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.comparacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparacao([NotNull] myCParser.ComparacaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.comparacao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparacao([NotNull] myCParser.ComparacaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.array_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_decl([NotNull] myCParser.Array_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.array_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_decl([NotNull] myCParser.Array_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.acesso_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcesso_array([NotNull] myCParser.Acesso_arrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.acesso_array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcesso_array([NotNull] myCParser.Acesso_arrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor([NotNull] myCParser.ForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor([NotNull] myCParser.ForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.if_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_else([NotNull] myCParser.If_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.if_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_else([NotNull] myCParser.If_elseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
