//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from myC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="myCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ImyCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] myCParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] myCParser.TipoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] myCParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] myCParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribuicao([NotNull] myCParser.AtribuicaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribuicao([NotNull] myCParser.AtribuicaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloco([NotNull] myCParser.BlocoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloco([NotNull] myCParser.BlocoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] myCParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] myCParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.incremento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncremento([NotNull] myCParser.IncrementoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.incremento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncremento([NotNull] myCParser.IncrementoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecls([NotNull] myCParser.DeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecls([NotNull] myCParser.DeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncao([NotNull] myCParser.FuncaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncao([NotNull] myCParser.FuncaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.declaracao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracao([NotNull] myCParser.DeclaracaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.declaracao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracao([NotNull] myCParser.DeclaracaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentos([NotNull] myCParser.ArgumentosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentos([NotNull] myCParser.ArgumentosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] myCParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] myCParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.identificador"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentificador([NotNull] myCParser.IdentificadorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.identificador"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentificador([NotNull] myCParser.IdentificadorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] myCParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] myCParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.negacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegacao([NotNull] myCParser.NegacaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.negacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegacao([NotNull] myCParser.NegacaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expressao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressao([NotNull] myCParser.ExpressaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expressao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressao([NotNull] myCParser.ExpressaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperador([NotNull] myCParser.OperadorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperador([NotNull] myCParser.OperadorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermo([NotNull] myCParser.TermoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermo([NotNull] myCParser.TermoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_aritmetica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_aritmetica([NotNull] myCParser.Expr_aritmeticaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_aritmetica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_aritmetica([NotNull] myCParser.Expr_aritmeticaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_relacional([NotNull] myCParser.Expr_relacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_relacional([NotNull] myCParser.Expr_relacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador_logico"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperador_logico([NotNull] myCParser.Operador_logicoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador_logico"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperador_logico([NotNull] myCParser.Operador_logicoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.condicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicao([NotNull] myCParser.CondicaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.condicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicao([NotNull] myCParser.CondicaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.expr_logica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_logica([NotNull] myCParser.Expr_logicaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.expr_logica"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_logica([NotNull] myCParser.Expr_logicaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.condicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicional([NotNull] myCParser.CondicionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.condicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicional([NotNull] myCParser.CondicionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] myCParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] myCParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetorno([NotNull] myCParser.RetornoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetorno([NotNull] myCParser.RetornoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.chamada_funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChamada_funcao([NotNull] myCParser.Chamada_funcaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.chamada_funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChamada_funcao([NotNull] myCParser.Chamada_funcaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntrada([NotNull] myCParser.EntradaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntrada([NotNull] myCParser.EntradaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.saida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaida([NotNull] myCParser.SaidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.saida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaida([NotNull] myCParser.SaidaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.selecao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelecao([NotNull] myCParser.SelecaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.selecao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelecao([NotNull] myCParser.SelecaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCasos([NotNull] myCParser.CasosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.casos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCasos([NotNull] myCParser.CasosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.operador_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperador_relacional([NotNull] myCParser.Operador_relacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.operador_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperador_relacional([NotNull] myCParser.Operador_relacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.comparacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparacao([NotNull] myCParser.ComparacaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.comparacao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparacao([NotNull] myCParser.ComparacaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.array_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_decl([NotNull] myCParser.Array_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.array_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_decl([NotNull] myCParser.Array_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.acesso_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcesso_array([NotNull] myCParser.Acesso_arrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.acesso_array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcesso_array([NotNull] myCParser.Acesso_arrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor([NotNull] myCParser.ForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor([NotNull] myCParser.ForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="myCParser.if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_else([NotNull] myCParser.If_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="myCParser.if_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_else([NotNull] myCParser.If_elseContext context);
}
